stages:
  - lint
  - test
  
variables:
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  

flake8:
  stage: lint
  image: python:3.7-alpine
  tags:
    - docker
  before_script:
    - pip --proxy=http://proxy22.udg.co.cu:3128 install -q flake8
  script:
    - flake8 almiky

tests:
  stage: tests
  tags:
    - docker
  script:
    - docker build -t almiky .
    - docker run almiky
