before_script:
 - source ~/.proxy
 - sproxy
 - python3 -m venv venv
 - source venv/bin/activate
 - pip install -r requeriments.txt
    
stages:
 - tests
 
run-all-tests:
 stage: tests
 script:
  - source run-test.sh
 tags:
  - test
  - python
  - coverage